package com.intland.codebeamer.integration.api.service.usergroup;

public enum UserGroupPermission {

	WIKI_EDIT_OWN_PAGE(1),
	ACCOUNT_ADMIN_OWN(2),
	ACCOUNT_ADMIN(4),
	ACCOUNT_ADDRESS_VIEW(8),
	ACCOUNT_COMPANY_VIEW(16),
	ACCOUNT_PHONE_VIEW(32),
	ACCOUNT_EMAIL_VIEW(64),
	ACCOUNT_SKILLS_VIEW(128),
	ACCOUNT_ROLE_VIEW(256),
	ACCOUNT_ROLE_ADMIN(512),
	DOCUMENT_ADD_GLOBAL(1024),
	LABEL_PUBLIC_CREATE(2048),
	LABEL_PUBLIC_ADMIN(4096),
	SYSTEM_PROJECT_CREATE(8192),
	SYSTEM_ADMIN(16384),
	SERVICE_DESK(32768),
	QUERIES_VIEW(65536),
	ACCOUNT_MODIFY_OWN_TIMEZONE_DATEFORMAT(131072),
	REVIEW(262144),
	ALLOW_COMMENT_SUBSCRIPTION(524288),
	API_PERMISSION(1048576),
	ONLY_API_PERMISSION(2097152),
	PROJECT_CATEGORY_ADMIN(4194304),
	MAINTENANCE_MODE_ACCESS(8388608),
	SHARED_FIELD_ADMIN(16777216),
	REVIEW_ADMINISTRATION(33554432);

	private Integer bitMaks;

	UserGroupPermission(Integer bitMaks) {
		this.bitMaks = bitMaks;
	}

	public static UserGroupPermission[] getRegularUserGroup() {
		return new UserGroupPermission[] { WIKI_EDIT_OWN_PAGE, ACCOUNT_ADMIN_OWN, ACCOUNT_ADDRESS_VIEW, ACCOUNT_COMPANY_VIEW,
				ACCOUNT_PHONE_VIEW, ACCOUNT_EMAIL_VIEW, ACCOUNT_SKILLS_VIEW, DOCUMENT_ADD_GLOBAL, LABEL_PUBLIC_CREATE,
				LABEL_PUBLIC_ADMIN, SYSTEM_PROJECT_CREATE, QUERIES_VIEW, REVIEW };
	}

	public static UserGroupPermission[] getSystemAdminGroup() {
		return new UserGroupPermission[] { WIKI_EDIT_OWN_PAGE, ACCOUNT_ADMIN_OWN, ACCOUNT_ADMIN, ACCOUNT_ADDRESS_VIEW,
				ACCOUNT_COMPANY_VIEW, ACCOUNT_PHONE_VIEW, ACCOUNT_EMAIL_VIEW, ACCOUNT_SKILLS_VIEW, ACCOUNT_ROLE_VIEW,
				ACCOUNT_ROLE_ADMIN, DOCUMENT_ADD_GLOBAL, LABEL_PUBLIC_CREATE, LABEL_PUBLIC_ADMIN, SYSTEM_PROJECT_CREATE,
				SYSTEM_ADMIN, QUERIES_VIEW, REVIEW, API_PERMISSION, PROJECT_CATEGORY_ADMIN, SHARED_FIELD_ADMIN };
	}
	
	public Integer getBitMaks() {
		return bitMaks;
	}

}
