package com.intland.codebeamer.integration.common.tracker;

public enum TrackerLayoutLabel {

	ID(0),
	TYPE(1),
	PRIORITY(2),
	NAME(3),
	SUBMITTED_AT(4),
	SUBMITTED_BY(6),
	ASSIGNED_TO(5),
	STATUS(7),
	START_DATE(8),
	END_DATE(9),
	ESTIMATED_H(10),
	STORY_POINTS(19),
	ACCRUED_H(18),
	SPENT_H(11),
	SPENT_ESTIMATED_H(12),
	CATEGORY(13),
	SEVERITY(14),
	RESOLUTION(15),
	PLATFORM(16),
	ASSIGNED_AT(29),
	SUBJECT(17),
	SUBSCRIBED_BY(20),
	TEAM(21),
	AREAS(22),
	MILESTONES(30),
	VERSION(31),
	SUPERVISOR(32),
	RELEASE_METHOD(33),
	BRANCH_ORIGINAL_ITEM(34),
	BRANCH_MASTER_ITEM(35),
	BRANCH_MERGE_CHAIN(36),
	MERGE_INFORMATION(37),
	FORMALITY(38),
	PROJECT_NAME(72),
	TRACKER_KEY_NAME(73),
	MODIFIED_AT(74),
	MODIFIED_BY(75),
	PARENT(76),
	REFERERS(78),
	CHILDREN(79),
	DESCRIPTION(80),
	DESCRIPTION_FORMAT_ID(84),
	CLOSED_AT(81),
	TEMPLATE(82),
	FLAGS(85),
	REFERRING_ISSUES_ID(86),
	REVISION(87),
	COMMENTS(90),
	ATTACHMENTS(88),
	REVIEWS(89),
	BODY(99);

	private int fieldId;

	TrackerLayoutLabel(int fieldId) {
		this.fieldId = fieldId;
	}

	public int getFieldId() {
		return fieldId;
	}
}